# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AUCGPA.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(250, 450)
        MainWindow.setMinimumSize(QtCore.QSize(250, 450))
        MainWindow.setMaximumSize(QtCore.QSize(250, 450))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(150, 40, 71, 221))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.splitter_2)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.splitter_2)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.splitter_2)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.splitter_2)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.splitter_2)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.splitter_2)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.splitter_2)
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.splitter_2)
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(20, 310, 71, 21))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(146, 312, 71, 21))
        self.label_18.setObjectName("label_18")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(40, 33, 91, 231))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.splitter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.splitter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.splitter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.splitter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.splitter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.splitter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.splitter)
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 250, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_17.setText(_translate("MainWindow", "Your CGPA :"))
        self.label_18.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "Semester 1         :"))
        self.label_2.setText(_translate("MainWindow", "Semester 2         : "))
        self.label_3.setText(_translate("MainWindow", "Semester 3         :"))
        self.label_4.setText(_translate("MainWindow", "Semester 4         :"))
        self.label_5.setText(_translate("MainWindow", "Semester 5         :"))
        self.label_6.setText(_translate("MainWindow", "Semester 6         :"))
        self.label_7.setText(_translate("MainWindow", "Semester 7         :"))
        self.label_8.setText(_translate("MainWindow", "Semester 8         :"))

        self.doubleSpinBox.setRange(1,10);
        self.doubleSpinBox.setDecimals(self,4);
        self.doubleSpinBox_2.setRange(1, 10);
        self.doubleSpinBox_2.setDecimals(self, 4);
        self.doubleSpinBox_3.setRange(1, 10);
        self.doubleSpinBox_3.setDecimals(self, 4);
        self.doubleSpinBox_4.setRange(1, 10);
        self.doubleSpinBox.setDecimals(self, 4);
        self.doubleSpinBox.setRange(1, 10);
        self.doubleSpinBox.setDecimals(self, 4);
        self.doubleSpinBox.setRange(1, 10);
        self.doubleSpinBox.setDecimals(self, 4);
        self.doubleSpinBox.setRange(1, 10);
        self.doubleSpinBox.setDecimals(self, 4);
        self.doubleSpinBox.setRange(1, 10);
        self.doubleSpinBox.setDecimals(self, 4);



import sys
app = QtWidgets.QApplication(sys.argv)
MainWindow = QtWidgets.QMainWindow()
ui = Ui_MainWindow()
ui.setupUi(MainWindow)
MainWindow.show()
sys.exit(app.exec_())
